apiVersion: v1
kind: Namespace
metadata:
  name: emojivoto
annotations:
  linkerd.io/inject: enabled
  config.linkerd.io/proxy-log-level: debug
  config.linkerd.io/disable-heartbeat: "true"
  config.linkerd.io/proxy-cpu-limit: "500m"
  config.linkerd.io/proxy-memory-limit: "128Mi"
  config.alpha.linkerd.io/proxy-enable-native-sidecar: true
